### ISSUE TITLE
Strapi 3.6.5 breaks after importing configuration files.

### ISSUE THREAD

**Issue by SalahAdDin** [boazpoolman/strapi-plugin-config-sync#15]
I had to change my working computer to a new one: yikes, the perfect time to test this plugin; well, every time i import even just one file, it breaks the setup a lot.

it can import some configurations, but it breaks many models, their panels, their content manager panels, etc., and i can't figure out why.

After importing settings, we found bugs like the next:
```
TypeError: Cannot read property 'reduce' of undefined
    at formatLayoutWithMetas (main.790d5f16.chunk.js:177692)
    at formatLayouts (main.790d5f16.chunk.js:177692)
    at _callee$ (main.790d5f16.chunk.js:177684)
    at tryCatch (main.790d5f16.chunk.js:81411)
    at Generator.invoke [as _invoke] (main.790d5f16.chunk.js:81641)
    at Generator.next (main.790d5f16.chunk.js:81466)
    at asyncGeneratorStep (main.790d5f16.chunk.js:18010)
    at _next (main.790d5f16.chunk.js:18032)
```

I tested it again, and i got the same problem again and again.

```shell
Strapi: v20.10.7
OS: macOS 11.5.1 20G80 x86_64 
```

About the stack:
```yaml
version: '3'
services:
  strapi:
    container_name: cancer_backend
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    container_name: cancer_db
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
      
  access_db:
    container_name: access_cancer_db
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8087:8081"
    environment:
      - DATABASE_URL=postgres://strapi:strapi@cancer_db:5432/postgres?sslmode=disable
      - VIRTUAL_HOST=strapi.db.localhost
      - VIRTUAL_PORT=8087
```

And packages used on the project:
```json
  "dependencies": {
    "knex": "0.21.18",
    "pg": "^8.6.0",
    "pg-connection-string": "^2.5.0",
    "strapi": "3.6.5",
    "strapi-admin": "3.6.5",
    "strapi-connector-bookshelf": "3.6.5",
    "strapi-plugin-config-sync": "^0.1.6",
    "strapi-plugin-content-manager": "3.6.5",
    "strapi-plugin-content-type-builder": "3.6.5",
    "strapi-plugin-email": "3.6.5",
    "strapi-plugin-graphql": "3.6.5",
    "strapi-plugin-i18n": "3.6.5",
    "strapi-plugin-upload": "3.6.5",
    "strapi-plugin-users-permissions": "3.6.5",
    "strapi-provider-email-amazon-ses": "^3.6.5",
    "strapi-provider-upload-aws-s3-plus-cdn": "^1.0.6",
    "strapi-utils": "3.6.5"
  },
```
Any help on this? Thanks.
